version: "3.7"
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - 3306:3306
    environment:
      MYSQL_USER: demo
      MYSQL_PASSWORD: clave123
      MYSQL_ROOT_PASSWORD: clave123
      MYSQL_DATABASE: ganbare
      TZ: America/Santiago
    volumes:
    - ./datadir:/var/lib/mysql
  #app:
    #image: lewickidev/gameshub:1.0.0
    #environment:
      #JAVA_OPS_APPEND: '-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dquarkus-profile=docker'
      #QUARKUS_DATASOURCE_JDBC_URL: 'jdbc:mysql://db:3306/gameshub?autoReconnect=true'
      #QUARKUS_DATASOURCE_USERNAME: gameshub
      #QUARKUS_DATASOURCE_PASSWORD: clave123
    #ports:
      #- "8080:8080"
    #depends_on:
      #- db