services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=caching_sha2_password
    ports:
     - 3306:3306
    environment:
      MYSQL_USER: demo
      MYSQL_PASSWORD: clave123
      MYSQL_ROOT_PASSWORD: clave123
      MYSQL_DATABASE: ganbare
      TZ: America/Santiago
    volumes:
    - ./datadir:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
  ganbare-core:
    image: ms-ganbare-core-api:1.0.0
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ganbare?autoReconnect=true
      SPRING_DATASOURCE_USERNAME: demo
      SPRING_DATASOURCE_PASSWORD: clave123
    depends_on:
      db:
        condition: service_healthy
    tty: true
    restart: always