server:
  port: 8080
spring:
  application:
    name: ms-ganbare-core-api
  datasource:
    url: jdbc:mysql://localhost:3306/ganbare
    username: root
    password: clave123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximumPoolSize: 10
      minimumIdle: 5
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  swagger:
    #http://localhost:8080/swagger-ui/index.html
    title: ms-ganbare-core-api
    description: This is the core of Ganbare application
    version: 1.0.0
