server:
  port: 8080
spring:
  application:
    name: ms-ganbare-core-api
  datasource:
    url: jdbc:mysql://localhost:3306/db_example
    username: root
    password: clave123
    hikari:
      maximumPoolSize: 10
      minimumIdle: 5
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
  jpa:
    hibernate:
      ddl-auto: update